services:
  - type: web
    name: air-pollution-tracker-backend
    env: node
    buildCommand: "npm install && npm run migrate"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
